import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    position: "absolute",
    right: 20,
    bottom: 30,
    backgroundColor: "transparent",
  },
  button: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#68A6DA",
    right: 12,
    bottom: 1,
    width: 64,
    height: 64,
    borderRadius: 40,
    elevation: 3,
    flexDirection: "row",
  },
  subButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#68A6DA",
    width: 48,
    height: 48,
    marginBottom: 10,
    marginRight: 10,
  },
  nameButton: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#68A6DA",
    right: 20,
    bottom: 1,
    width: 64,
    height: 64,
    borderRadius: 40,
    elevation: 3,
    flexDirection: "row",
  },
  subNameButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    borderRadius: 10,
    elevation: 3,
    right: 60,
    height: 45,
    marginRight: -10,
    paddingRight: 50,
    paddingLeft: 20,
  },
  addPill: {
    height: 48,
    width: 275,
    backgroundColor: "#FFFFFF",
    elevation: 3,
    borderRadius: 24,
    justifyContent: "center",
    paddingLeft: 15,
    marginBottom: 23,
    marginRight: 25,
  },
  textAddPill: {
    fontFamily: "Lexend_400Regular",
    fontSize: 16,
  },
  addDrawer: {
    height: 48,
    width: 215,
    backgroundColor: "#FFFFFF",
    elevation: 3,
    borderRadius: 24,
    justifyContent: "center",
    paddingLeft: 15,
    marginBottom: 81,
    marginLeft: 14,
  },
  textAddDrawer: {
    fontFamily: "Lexend_400Regular",
    fontSize: 16,
  },
});

export default styles;
